### ISSUE TITLE
Sortable?

### ISSUE THREAD

**Issue by cfjedimaster** [joshknutson/coldfusion-debug#3]
Should the tables be sortable? I see code in there that seems to imply it - but clicking on table columns doesn't change the sort.

**Comment by joshknutson** [comment]
Were you using the collapsible template?
Which debug option were you using?

It's been a while since I have looked at the code, but I could plop in a small function to add basic sorting.

**Comment by joshknutson** [comment]
Were you using the collapsible template?
Which debug option were you using?

It's been a while since I have looked at the code, but I could plop in a small function to add basic sorting.

**Comment by cfjedimaster** [comment]
It's the collapsible one. As I said, it isn't working for me. Anything I should look for?

**Comment by joshknutson** [comment]
Might be some conflicting javascript, would you be willing to include a screenshot...or gif? with the console open.

**Comment by cfjedimaster** [comment]
Can't share a screenshot. sortable.min.js *is* loaded. No errors relevant to the library are in the console. Does it expect jQuery to exist perhaps?

**Comment by joshknutson** [comment]
Oh yeah, your right, I'll see if I can eliminate that

**Comment by joshknutson** [comment]
Code committed for a vanilla js solution that is still basic and allow for some rudimentary sorting
